### ISSUE TITLE
Clever deploy not working on docker

### ISSUE THREAD

**Issue by luisRubiera** [CleverCloud/clever-tools#190]
Deploying with Clever CLI works, but i try to do it from a gitlab runner (Docker image). this works with:
`./clever deploy -a ${MYPROJECT}`
`clever: ../vendor/libgit2/src/transports/http.c:380: int on_headers_complete(http_parser *): Assertion t->cred' failed.`
`/usr/bin/bash: line 59: 3449 Aborted (core dumped) ./clever deploy -a ${MYPROJECT}`

info about the docker image:
`uname -a
Linux bdbc6d40a302 4.13.0-31-generic #34~16.04.1-Ubuntu SMP Fri Jan 19 17:11:01 UTC 2018 x86_64 GNU/Linux`

image name : `debian:rc-buggy-20171210`

dependencies added after container is up: ` libcurl4-gnutls-dev`
(`apt-get update && apt-get install -y libcurl4-gnutls-dev`)

clever version:
`md5sum clever `
`d0b31f7ff90c801788f601c703bd853b clever`

file added to image/git:
`clever`
`nodegit.node`
`.clever.json`

**Comment by divarvel** [comment]
Can you try with a different base image ?

**Comment by luisRubiera** [comment]
result with `debian:latest`
`./clever deploy -a dev
clever: ../vendor/libgit2/src/transports/http.c:380: int on_headers_complete(http_parser *): Assertion t->cred failed.
/bin/bash: line 59:  3932 Aborted                 (core dumped) ./clever deploy -a dev
`

**Comment by BlackYoup** [comment]
Would you happen to have a Dockerfile which reproduce your problem ?

**Comment by luisRubiera** [comment]
Im using gitlab-ci , so its not a Dockerfile, or i can say is the basic image + the following scripts:

```
image: debian:latest

deploy_app_develop:
  stage: deploy
  tags:
    - docker
  only:
    - develop
  script:
    - 'apt-get update'
    - 'apt-get install -y libcurl4-gnutls-dev'
    - './clever deploy -a bs-dev'
```

you could say is just the `image` , `apt-get update & install` and `clever deploy`.

**Comment by jeanBaptisteCaron** [comment]
I have the same issue here, my runner is on a ubuntu server (following this : https://docs.gitlab.com/runner/install/linux-manually.html ), then i have login in my clever app with : 
```
/clever login --token CLEVER_TOKEN --secret CLEVER_SECRET 
```
then : 
```
./clever link  APP_ID
```
 and my gitlab-ci contain : 
```
deploy:clevercloud:
  image: ubuntu
  stage: deploy
  tags:
    - sh
  only:
    - /develop/
  script:
    - 'clever deploy -a dev'
```
